<!DOCTYPE html>
<html lang="uk">
<head>
  <meta charset="UTF-8">
  <title>Вхід</title>
  <link rel="stylesheet" href="/style/styles.css">
</head>
<body>

<header>
  <div class="logo">Вхід до системи</div>
  <nav id="nav-menu">
    <a href="/workload">Навантаження</a>
  </nav>
</header>


<form>
  <label for="username">Логін</label>
  <input type="text" id="username" name="username">

  <label for="password">Пароль</label>
  <input type="password" id="password" name="password">


  <button href="/" type="submit">Увійти</button>
  <a href="/register" type="submit">Зареєструватись</a>

</form>

</body>
</html>
